apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - argoWorkflowsInsecure=true
  - cfHost=https://app-staging.codefresh.io
  - cors=https://app-staging.codefresh.io
  - env=production
  name: cap-app-proxy-cm
kind: Kustomization
namespace: staging-runtime-12-05-demo-cluster
resources:
- ../../base
- ingress.yaml
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.5/controller.yaml
images:
  - name: quay.io/codefresh/cap-app-proxy
    newName: quay.io/codefresh/cap-app-proxy
    newTag: CR-11110-test4
